Repository tutti-tutti/tutti-client, pull requests merged in 2025-04, with the labels that each got.

#211 [✨ design] 일부 컴포넌트에서의 스타일 수정 (#210)
  src/app/(root)/faqs/page.tsx
  src/components/cart/CartInfo.tsx
  src/components/faqs/FaqAccordion.tsx
  src/components/faqs/FaqAccordionAnswer.tsx
Labels: 💅 design

#213 [✨ design] 상품별 리뷰 모바일 디자인 추가
  src/app/(root)/products/[productId]/page.tsx
  src/components/common/Icon.tsx
  src/components/icons/ThinkingFaceIcon.tsx
  src/components/icons/index.ts
  src/components/products/product-detail/ClientProductDetail.tsx
  src/components/products/product-detail/ProductDetailItem.tsx
  src/components/products/product-detail/ProductHeader.tsx
  src/components/reviews/product-review/AverageReview.tsx
  src/components/reviews/product-review/ReviewBadge.tsx
  src/components/reviews/product-review/ReviewItem.tsx
  src/components/reviews/product-review/ReviewLikeButton.tsx
  src/services/reviewService.ts
  src/types/iconType.ts
  src/types/productType.ts
  src/types/reviewType.ts
Labels: ✨ feat

#212 [✨ feat] 리뷰 조회에 무한 스크롤 적용
  src/app/(root)/products/[productId]/page.tsx
  src/components/reviews/product-review/AverageReview.tsx
  src/components/reviews/product-review/ProductReview.tsx
  src/components/reviews/product-review/ReviewFilter.tsx
  src/components/reviews/product-review/ReviewItem.tsx
  src/components/reviews/product-review/ReviewLikeButton.tsx
  src/components/reviews/product-review/ReviewList.tsx
  src/constants/endpoints.ts
  src/queries/index.ts
  src/queries/reviewQueries.ts
  src/server-actions/index.ts
  src/server-actions/review/fetchReviewsAction.ts
  src/services/reviewService.ts
  src/stores/index.ts
  src/stores/reviewServerStore.ts
  src/types/reviewType.ts
  src/utils/index.ts
  src/utils/reviewCache.ts
Labels: ✨ feat

#209 [✨ feat] 주문/결제 배송지 입력 처리
  src/app/(root)/checkout/page.tsx
  src/components/common/button/Button.tsx
  src/components/orders-payments/DeliveryAddress.tsx
  src/components/orders-payments/OrderHistoryList/OrderHistoryList.tsx
  src/components/orders-payments/OrderHistoryList/OrderHistoryListGroup.tsx
  src/components/orders-payments/OrderProductList/OrderProductList.tsx
  src/components/orders-payments/OrderProductList/OrderProductListGroup.tsx
  src/components/orders-payments/PaymentMethodSelector.tsx
  src/components/orders-payments/ProductAmoutInfo.tsx
  src/components/orders-payments/ShippingAddressForm.tsx
  src/components/orders-payments/index.ts
  src/components/reviews/create-review/ReviewProductInfo.tsx
  src/constants/index.ts
  src/constants/orders.ts
  src/services/ordersService.ts
  src/stores/index.ts
  src/stores/shippingAddressStore.ts
  src/stories/orders/OrderProductListGroup.stories.tsx
  src/styles/feature/index.css
  src/styles/feature/orders.css
  src/styles/globals.css
  src/styles/token/index.css
  src/types/formDataType.ts
  src/types/index.ts
  src/types/kakao.d.ts
  src/types/paymentsType.ts
  src/utils/dataTransformUtils.ts
Labels: ✨ feat

#217 [🐞 hotfix] 배포 빌드 에러 수정
  src/queries/ordersQueries.ts
Labels: 🐞 hotfix

#218 [♻️ refactor] 카테고리명이 없을 경우의 추천 상품 메시지 변경 (#216)
  src/components/products/RecommendProductList.tsx
Labels: ♻️ refactor

#222 [✨ feat] 파비콘 로고로 변경 (#221)
  src/app/(root)/page.tsx
  src/app/favicon.ico
Labels: ✨ feat

#223 [✨ feat] 주문 상세 조회와 CTA와 주문/결제 취소 기능(환불 api) 적용
  src/app/(root)/my/orders/[orderId]/page.tsx
  src/app/api/refund/request/route.tsx
  src/components/common/Badge.tsx
  src/components/orders-payments/OrderHistoryList/OrderHistoryList.tsx
  src/components/orders-payments/OrderHistoryList/OrderHistoryListGroup.tsx
  src/components/orders-payments/OrderHistoryList/OrderHistoryListGroupHeader.tsx
  src/components/orders-payments/OrderHistoryList/OrdersActions.tsx
  src/components/orders-payments/OrderHistoryList/OrdersExtraActions.tsx
  src/components/orders-payments/OrderHistoryList/index.ts
  src/components/orders-payments/OrderStatusBadge.tsx
  src/components/orders-payments/OrderTableInfoSection.tsx
  src/components/orders-payments/index.ts
  src/components/products/ProductThumbnail.tsx
  src/constants/endpoints.ts
  src/constants/paths.ts
  src/services/paymentsService.ts
  src/types/badgeType.ts
  src/types/index.ts
  src/types/ordersType.ts
  src/types/paymentsType.ts
  src/utils/dataTransformUtils.ts
Labels: ✨ feat

#228 [✨ design] 헤더 디자인 수정에 따라 스타일 수정 (#227)
  src/components/common/Logo.tsx
  src/components/common/header/NavIcon.tsx
  src/components/common/header/SearchInput.tsx
  src/components/layout/header/Header.tsx
  src/components/layout/header/HeaderNavigation.tsx
  src/stories/NavIcon.stories.tsx
Labels: 💅 design

#226 [🔧 fix] tosspayments success redirection 페이지에서 500에러가 나는 현상
  src/app/(root)/checkout/success/page.tsx
  src/types/ordersType.ts
  src/types/paymentsType.ts
Labels: 🔧 fix, 🐞 hotfix

#230 [✨ feat] auth 서버 에러 핸들링
  src/components/auth/ResetPwForm.tsx
  src/components/auth/SigninForm.tsx
  src/components/auth/SignupForm.tsx
  src/constants/auth.ts
  src/schemas/auth/authSchema.ts
  src/server-actions/auth/requestVerificationCodeAction.ts
  src/server-actions/auth/resetPwAction.ts
  src/server-actions/auth/signinAction.ts
  src/server-actions/auth/signupAction.ts
  src/server-actions/auth/verifyCodeAction.ts
  src/services/authService.ts
  src/types/authType.ts
Labels: ✨ feat

#237 [✨ feat] 동적 라우트를 가진 상품 상세 페이지를 SSG (#236)
  src/app/(root)/products/[productId]/page.tsx
  src/lib/axios.ts
  src/services/productService.ts
Labels: ✨ feat

#241 [✨ feat] 인증 페이지 리다이렉션
  src/components/auth/ResetPwForm.tsx
  src/components/auth/SigninForm.tsx
  src/components/auth/SignupForm.tsx
  src/server-actions/auth/resetPwAction.ts
  src/server-actions/auth/signinAction.ts
  src/server-actions/auth/signupAction.ts
Labels: ✨ feat

#238 [🔧 fix] 비회원 리뷰 좋아요 시 회원 기능임을 표시, 리뷰 정렬 텍스트 활성화 수정
  src/components/faqs/CategoryFilterItem.tsx
  src/components/faqs/FaqAccordionItemQuestion.tsx
  src/components/faqs/SubCategoryFilterItem.tsx
  src/components/reviews/product-review/ProductReview.tsx
  src/components/reviews/product-review/ReviewItem.tsx
  src/components/reviews/product-review/ReviewList.tsx
  src/components/reviews/product-review/ReviewRatingBar.tsx
  src/components/reviews/product-review/ReviewSort.tsx
  src/server-actions/review/sentimentFeedbackAction.ts
Labels: ✨ feat

#235 [✨ feat] 주문 내역/상세 쿼리옵션으로 일관된 데이터와 UI 관리
  src/app/(root)/my/orders/[orderId]/page.tsx
  src/app/(root)/my/orders/page.tsx
  src/components/common/Badge.tsx
  src/components/orders-payments/OrderHistoryList/OrderDetailClientWrapper.tsx
  src/components/orders-payments/OrderHistoryList/OrderHistoryClientWrapper.tsx
  src/components/orders-payments/OrderHistoryList/OrderHistoryList.tsx
  src/components/orders-payments/OrderHistoryList/OrderHistoryListGroup.tsx
  src/components/orders-payments/OrderHistoryList/OrderHistoryListGroupHeader.tsx
  src/components/orders-payments/OrderHistoryList/OrdersActions.tsx
  src/components/orders-payments/OrderHistoryList/OrdersExtraActions.tsx
  src/components/orders-payments/OrderHistoryList/index.ts
  src/components/orders-payments/OrderStatusBadge.tsx
  src/components/orders-payments/ProductAmoutInfo.tsx
  src/hooks/index.ts
  src/hooks/queries/.gitkeep
  src/hooks/queries/index.ts
  src/hooks/queries/useRefundMutation.ts
  src/types/ordersType.ts
Labels: 💅 design, ✨ feat, 🔧 fix

#247 [🔧 fix] 상품 도메인 간단한 수정사항 반영 (#246)
  src/app/(root)/cart/page.tsx
  src/app/(root)/products/[productId]/page.tsx
Labels: 🔧 fix

#249 [✨ feat] 헤더에 로그인 상태 처리 및 로그아웃 기능 삽입
  src/app/(root)/layout.tsx
  src/app/api/members/mypage/route.ts
  src/components/common/button/LogoutButton.tsx
  src/components/layout/header/Header.tsx
  src/components/layout/header/TextHeader.tsx
  src/constants/queries.ts
  src/queries/authMutations.ts
  src/queries/index.ts
  src/queries/memberQueries.ts
  src/server-actions/auth/signoutAction.ts
  src/server-actions/index.ts
  src/stories/Header.stories.tsx
  src/stories/TextHeader.stories.ts
Labels: ✨ feat

#252 [✨ feat] 비회원 리뷰 좋아요 시 토스트로 알림
  src/components/common/Toast.tsx
  src/components/reviews/product-review/ProductReview.tsx
  src/components/reviews/product-review/ReviewItem.tsx
  src/components/reviews/product-review/ReviewLikeButton.tsx
  src/utils/toast.tsx
Labels: ✨ feat

#253 [💅 design] 상품 상세 옵션이 없는 경우 보더가 딱 붙는 현상 수정
  src/components/products/product-detail/ProductDetailItem.tsx
  src/components/products/product-detail/ProductHeader.tsx
  src/components/products/product-detail/ProductOptions.tsx
Labels: 💅 design, 🔧 fix

#258 [🐞 hotfix] 소셜로그인 성공 시 jwt가 쿠키에 저장되지 않는 문제 해결
  src/lib/nextAuth.ts
  src/services/tokenService.ts
Labels: 🐞 hotfix

#261 [🔧 fix] 상품 상세 페이지에서 상품 구매할 때 회원 여부 판별 (#260)
  src/components/cart/CartInfo.tsx
  src/components/products/product-detail/ProductActions.tsx
Labels: 🔧 fix

#264 [🔧 fix] 리뷰 작성 시 상품 데이터를 페칭하도록 수정
  src/components/reviews/create-review/ReviewProductInfo.tsx
  src/services/reviewService.ts
Labels: ✨ feat

#266 [✨ design] No Data UI 컴포넌트 생성
  src/app/(root)/my/orders/page.tsx
  src/components/common/NoData.tsx
  src/components/common/index.ts
Labels: 💅 design

#262 [⚙️ chore] 5차 마일스톤 일부 수정 사항 반영
  src/app/(root)/my/orders/page.tsx
  src/components/cart/CartInfo.tsx
  src/components/common/NoData.tsx
  src/components/common/index.ts
  src/components/products/product-detail/ProductActions.tsx
  src/components/reviews/create-review/ReviewProductInfo.tsx
  src/lib/nextAuth.ts
  src/services/reviewService.ts
  src/services/tokenService.ts
Labels: ⚙️ chore

#268 [📜 docs] 리드미 추가 (#267)
  README.md
Labels: 📜 docs

#270 docs: 리드미 파일에 서비스 소개와 개발환경 안내 추가 (#269)
  README.md
Labels: 📜 docs

#275 [♻️ refactor] 상품, 장바구니 도메인에서 한글로 하드코딩된 것 상수로 모듈화 (#273)
  src/components/cart/CartHeader.tsx
  src/components/cart/CartInfo.tsx
  src/components/cart/CartItem.tsx
  src/components/cart/CartItemPrice.tsx
  src/components/cart/CartItemQuantity.tsx
  src/components/cart/CartList.tsx
  src/components/cart/CartPaymentInfo.tsx
  src/components/category/ProductCategory.tsx
  src/components/common/Dropdown.tsx
  src/components/common/button/MoreViewButton.tsx
  src/components/products/ProductItem.tsx
  src/components/products/RecommendCarousel.tsx
  src/components/products/RecommendProductItem.tsx
  src/components/products/RecommendProductList.tsx
  src/components/products/product-detail/ProductActions.tsx
  src/components/products/product-detail/ProductDetailInfo.tsx
  src/components/products/product-detail/ProductHeader.tsx
  src/components/products/product-detail/ProductOptions.tsx
  src/components/products/product-detail/ProductPrice.tsx
  src/components/products/product-detail/ProductQuantity.tsx
  src/constants/cart.ts
  src/constants/index.ts
  src/constants/products.ts
  src/hooks/common/useCart.ts
  src/services/cartService.ts
Labels: ♻️ refactor

#278 [✨ feat] 상품 리스트에서도 리뷰 별점과 개수 볼 수 있도록 변경 (#276)
  src/app/(root)/products/page.tsx
  src/app/layout.tsx
  src/assets/images/open_graph.jpg
  src/components/cart/CartInfo.tsx
  src/components/category/CategoryProductList.tsx
  src/components/category/ClientCategoryProductList.tsx
  src/components/products/ClientProductList.tsx
  src/components/products/ProductItem.tsx
  src/components/products/ProductList.tsx
  src/components/products/skeleton/ProductListSkeleton.tsx
  src/constants/base.ts
  src/constants/endpoints.ts
  src/constants/index.ts
  src/constants/products.ts
  src/constants/queries.ts
  src/hooks/common/index.ts
  src/hooks/common/useProductReviews.ts
  src/queries/productsQueries.ts
  src/queries/reviewQueries.ts
  src/server-actions/index.ts
  src/server-actions/review/productReviewAction.ts
  src/stores/productServerStore.ts
  src/stories/product/ProductItem.stories.tsx
  src/stories/product/ProductList.stories.tsx
Labels: ✨ feat

#277 [♻️ refactor] 회원 컴포넌트 및 기능 리팩토링
  src/app/(auth)/reset-password/page.tsx
  src/app/(auth)/signin/page.tsx
  src/app/(auth)/signup/page.tsx
  src/components/auth/AuthForm.tsx
  src/components/auth/AuthFormContent.tsx
  src/components/auth/AuthSubmitButton.tsx
  src/components/auth/ResetPwForm.tsx
  src/components/auth/SigninForm.tsx
  src/components/auth/SignupForm.tsx
  src/components/auth/index.ts
  src/constants/auth.ts
  src/constants/errorMessages.ts
  src/constants/index.ts
  src/constants/paths.ts
  src/hooks/index.ts
  src/hooks/useAuthSteps.ts
  src/schemas/auth/index.ts
  src/schemas/auth/requestVerifySchema.ts
  src/schemas/auth/resetPwSchema.ts
  src/schemas/auth/signinSchema.ts
  src/schemas/auth/signupSchema.ts
  src/schemas/auth/verifyEmailSchema.ts
  src/server-actions/auth/handleServerError.ts
  src/server-actions/auth/handleValidationError.ts
  src/server-actions/auth/requestVerificationCodeAction.ts
  src/server-actions/auth/resetPwAction.ts
  src/server-actions/auth/signinAction.ts
  src/server-actions/auth/signupAction.ts
  src/server-actions/auth/verifyCodeAction.ts
  src/types/authType.ts
Labels: ♻️ refactor

#280 [✨ feat] 미들웨어를 이용한 라우팅 보호 및 보안
  src/app/error/authorized/page.tsx
  src/app/error/restricted/page.tsx
  src/app/error/unauthorized/page.tsx
  src/app/not-found.tsx
  src/components/common/ErrorPageTemplate.tsx
  src/components/common/index.ts
  src/constants/base.ts
  src/constants/errorMessages.ts
  src/constants/index.ts
  src/constants/paths.ts
  src/middleware.ts
Labels: ✨ feat

#283 [✨ feat] 상품 상세 페이지에서 옵션 선택 시 스택처럼 쌓이도록 추가 (#282)
  src/app/api/cart/[cartItemId]/route.ts
  src/app/api/cart/route.ts
  src/app/api/categories/[categoryId]/products/route.ts
  src/app/api/products/[productId]/route.ts
  src/components/products/product-detail/ProductActions.tsx
  src/components/products/product-detail/ProductDetailItem.tsx
  src/components/products/product-detail/ProductOptions.tsx
  src/components/products/product-detail/ProductPrice.tsx
  src/components/products/product-detail/ProductQuantity.tsx
  src/components/products/product-detail/ProductSelectInfo.tsx
  src/constants/cart.ts
  src/constants/products.ts
  src/hooks/common/index.ts
  src/hooks/common/useProductOptions.ts
  src/lib/axios.ts
  src/services/cartService.ts
  src/services/productService.ts
  src/types/productType.ts
Labels: ✨ feat

#287 [♻️ refactor] 주문 내역과 주문 상세페이지의 중복 코드를 컴포넌트 재사용 및 상수 모듈화
  src/app/(root)/my/orders/[orderId]/page.tsx
  src/app/(root)/my/orders/page.tsx
  src/app/(root)/my/review/write/[orderId]/[productItemId]/page.tsx
  src/app/api/refund/request/route.tsx
  src/components/orders-payments/CheckoutHeader.tsx
  src/components/orders-payments/OrderHistoryList/AllCancelButton.tsx
  src/components/orders-payments/OrderHistoryList/OrderDetailClientWrapper.tsx
  src/components/orders-payments/OrderHistoryList/OrderDetailListGroupHeader.tsx
  src/components/orders-payments/OrderHistoryList/OrderGroupHeader.tsx
  src/components/orders-payments/OrderHistoryList/OrderHistoryClientWrapper.tsx
  src/components/orders-payments/OrderHistoryList/OrderHistoryList.tsx
  src/components/orders-payments/OrderHistoryList/OrderHistoryListGroup.tsx
  src/components/orders-payments/OrderHistoryList/OrderHistoryListGroupHeader.tsx
  src/components/orders-payments/OrderHistoryList/OrderIdHeading.tsx
  src/components/orders-payments/OrderHistoryList/OrdersActions.tsx
  src/components/orders-payments/OrderHistoryList/OrdersExtraActions.tsx
  src/components/orders-payments/OrderHistoryList/index.ts
  src/components/orders-payments/OrderProductList/OrderProductList.tsx
  src/components/orders-payments/OrderProductList/OrderProductListGroup.tsx
  src/components/orders-payments/ProductAmoutInfo.tsx
  src/constants/orders.ts
  src/constants/paths.ts
  src/constants/queries.ts
  src/constants/review.ts
  src/hooks/queries/useRefundMutation.ts
  src/middleware.ts
  src/queries/ordersQueries.ts
  src/queries/paymentsQueries.ts
  src/services/paymentsService.ts
  src/stories/orders/OrderStatusBadge.stories.tsx
  src/types/ordersType.ts
  src/types/paymentsType.ts
  src/utils/dataTransformUtils.ts
  src/utils/format.ts
Labels: ♻️ refactor

#291 [⚙️ chore] 스토리북 meta title 별로 폴더 구조 변경 (#288)
  src/apis/.gitkeep
  src/components/common/ClickText.tsx
  src/components/common/header/index.ts
  src/components/common/index.ts
  src/components/layout/header/NavIcon.tsx
  src/components/layout/header/SearchInput.tsx
  src/components/layout/header/index.ts
  src/stories/common/Badge.stories.tsx
  src/stories/common/Checkbox.stories.ts
  src/stories/common/ClickText.stories.ts
  src/stories/common/Dropdown.stories.tsx
  src/stories/common/Input.stories.ts
  src/stories/common/RadioOption.stories.tsx
  src/stories/common/StepProgressBar.stories.ts
  src/stories/common/Switch.stories.tsx
  src/stories/common/Toast.stories.tsx
  src/stories/layout/footer/Footer.stories.ts
  src/stories/layout/header/Header.stories.tsx
  src/stories/layout/header/NavIcon.stories.tsx
  src/stories/layout/header/SearchInput.stories.ts
  src/stories/layout/header/TextHeader.stories.ts
  src/stories/pages/NotFoundPage.stories.tsx
  src/stories/pages/auth/ResetPasswordPage.stories.ts
  src/stories/pages/auth/SigninPage.stories.ts
Labels: ⚙️ chore

#295 [🐞 hotfix] 주문결제 api 스키마 변경 반영
  src/app/(root)/my/orders/page.tsx
  src/components/orders-payments/OrderHistoryList/AllCancelButton.tsx
  src/components/orders-payments/OrderHistoryList/OrderDetailClientWrapper.tsx
  src/components/orders-payments/OrderHistoryList/OrderGroupHeader.tsx
  src/components/orders-payments/OrderHistoryList/OrderHistoryClientWrapper.tsx
  src/components/orders-payments/OrderHistoryList/OrderHistoryList.tsx
  src/components/orders-payments/OrderHistoryList/OrderHistoryListGroup.tsx
  src/components/orders-payments/OrderHistoryList/OrderIdHeading.tsx
  src/components/orders-payments/OrderHistoryList/OrdersActions.tsx
  src/components/orders-payments/OrderHistoryList/OrdersExtraActions.tsx
  src/components/orders-payments/PaymentMethodSelector.tsx
  src/hooks/queries/useRefundMutation.ts
  src/mocks/orders.ts
  src/queries/ordersQueries.ts
  src/services/ordersService.ts
  src/types/ordersType.ts
  src/types/paymentsType.ts
  src/utils/dataTransformUtils.ts
Labels: 🔧 fix, 🐞 hotfix

#290 [✨ feat] axios에 Next.js의 fetch api 적용
  next.config.ts
  package.json
  pnpm-lock.yaml
  src/hooks/common/useRevalidateServerClient.ts
  src/lib/axios.ts
  src/server-actions/index.ts
  src/server-actions/revalidateServerCache.ts
Labels: ✨ feat

#300 [♻️ refactor] 회원 장바구니 추가 시 maxQuantity 까지 추가되도록 수정 (#298)
  src/components/cart/CartItem.tsx
  src/components/cart/CartItemHeader.tsx
  src/components/cart/CartItemImage.tsx
  src/components/cart/CartItemSkeleton.tsx
  src/components/cart/CartList.tsx
  src/components/common/NoData.tsx
  src/components/products/product-detail/ProductActions.tsx
  src/mocks/cart.ts
  src/services/cartService.ts
  src/stores/createCartMocks.ts
  src/types/cartType.ts
Labels: ♻️ refactor

#301 [♻️ refactor] 중복되는 페이지 헤더 스타일 컴포넌트로 재사용 가능하도록 처리 및 스토리북 추가
  src/app/(root)/cart/page.tsx
  src/app/(root)/checkout/page.tsx
  src/components/cart/CartHeader.tsx
  src/components/cart/CartInfo.tsx
  src/components/cart/index.ts
  src/components/common/PageContentHeader.tsx
  src/components/common/index.ts
  src/components/mypage/MypageHeader.tsx
  src/components/orders-payments/CheckoutHeader.tsx
  src/stories/common/PageContentHeader.stories.tsx
  src/stories/common/PageTitle.stories.tsx
Labels: ♻️ refactor

#303 [⚙️ chore] 스토리북에서 레이아웃이 맞지 않는 스토리 UI 일괄 수정
  src/stories/cart/CartInfo.stories.tsx
  src/stories/orders/OrderProductListGroup.stories.tsx
  src/stories/pages/auth/ResetPasswordPage.stories.tsx
  src/stories/pages/auth/SigninPage.stories.tsx
  src/stories/product/ProductDetailItem.stories.tsx
  src/stories/product/ProductList.stories.tsx
  src/stories/product/RecommendProductList.stories.tsx
Labels: ⚙️ chore, 💅 design

#304 [✨ feat] 주문내역, 주문상세 페이지의 주문 리스트 상세페이지 연결, 리뷰작성시 productId 전달, 장바구니 추가 기능 추가
  src/components/cart/CartItemHeader.tsx
  src/components/cart/CartItemImage.tsx
  src/components/orders-payments/OrderHistoryList/OrderHistoryList.tsx
  src/components/orders-payments/OrderHistoryList/OrdersExtraActions.tsx
  src/components/products/ProductItem.tsx
  src/components/products/RecommendProductItem.tsx
  src/components/products/product-detail/ProductActions.tsx
  src/constants/paths.ts
  src/hooks/common/index.ts
  src/hooks/common/useAddCart.ts
  src/stories/orders/OrderProductListGroup.stories.tsx
  src/types/ordersType.ts
Labels: ✨ feat, ♻️ refactor

#310 [♻️ refactor] 장바구니 `productName` 필드명 수정에 따른 코드 수정 (#309)
  src/components/cart/CartItem.tsx
  src/components/cart/CartItemHeader.tsx
  src/components/cart/CartItemImage.tsx
  src/mocks/cart.ts
  src/services/cartService.ts
  src/stores/createCartMocks.ts
  src/types/cartType.ts
Labels: ♻️ refactor

#314 [✨ feat] Next.js 서버 캐싱과 다양한 렌더링 방식 활용을 위해 axios의 기능을 가진 fetch-api 라이브러리 구현
  src/lib/fetchos/fetchos.ts
  src/lib/fetchos/fetchosError.ts
  src/lib/fetchos/fetchosInstance.ts
  src/lib/fetchos/fetchosTypes.ts
  src/lib/fetchos/index.ts
  src/lib/index.ts
Labels: ✨ feat

#313 [✨ feat] 상품 검색 api 연동 및 페이지 구현 (#312)
  src/app/(root)/products/page.tsx
  src/app/api/products/search-list/route.ts
  src/components/index.ts
  src/components/layout/header/Header.tsx
  src/components/layout/header/SearchInput.tsx
  src/components/search/ClientSearchResultList.tsx
  src/components/search/SearchResultList.tsx
  src/components/search/index.ts
  src/constants/endpoints.ts
  src/constants/products.ts
  src/queries/index.ts
  src/queries/searchQueries.ts
  src/services/productService.ts
Labels: ✨ feat

#317 [🔧 fix] 주문결제 API 수정사항 반영
  src/components/checkout/PaymentMethodSelector.tsx
  src/components/orders-payments/OrderTableInfoSection.tsx
  src/constants/endpoints.ts
  src/types/ordersType.ts
  src/types/paymentsType.ts
Labels: 🔧 fix, 🐞 hotfix

#315 [✨ feat] breadcrumb 컴포넌트의 링크 및 텍스트가 자동완성 되도록 설정 및 paths 상수 구조화하여 pageRouter 인스턴스 생성
  src/app/(auth)/layout.tsx
  src/app/(root)/checkout/success/page.tsx
  src/components/cart/CartHeader.tsx
  src/components/checkout/CheckoutHeader.tsx
  src/components/common/Breadcrumb.tsx
  src/components/mypage/MypageHeader.tsx
  src/components/orders-payments/OrderHistoryList/OrderIdHeading.tsx
  src/components/orders-payments/OrderHistoryList/OrdersExtraActions.tsx
  src/constants/paths.ts
  src/navigator/index.ts
  src/navigator/pagePath.ts
  src/types/breadcrumbType.ts
  src/types/index.ts
  src/utils/genertate.ts
Labels: ✨ feat, ♻️ refactor
