Repository tutti-tutti/tutti-client, pull requests merged in 2025-03, with the labels that each got.

#19 [🔧 fix] 빌드 시 발생하는 quot 오류 수정 (#18)
  src/stories/Page.tsx
Labels: 🔧 fix

#20 [⚙️ chore] 깃허브 Organization 레포지토리 vercel 자동 배포 (#17)
  .github/workflows/deploy.yml
  build.sh
Labels: ⚙️ chore

#22 [⚙️ chore] main 브랜치로 merge 시 액션 실행 테스트 (#21)
  .github/workflows/chromatic.yml
  .github/workflows/deploy.yml
  .nvmrc
  .storybook/main.ts
  build.sh
  package.json
  pnpm-lock.yaml
  src/app/fonts/GeistMonoVF.woff
  src/app/fonts/GeistVF.woff
  src/app/fonts/PretendardVariable.woff2
  src/app/layout.tsx
  src/stories/Button.stories.ts
  src/stories/Header.stories.ts
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/styles/globals.css
Labels: ⚙️ chore

#25 [⚙️ chore] main 브랜치로 머지 시 액션 실행 테스트2
  package.json
  public/mockServiceWorker.js
  src/app/layout.tsx
  src/constants/endpoints.ts
  src/constants/index.ts
  src/lib/msw/.gitkeep
  src/lib/msw/handlers/index.ts
  src/lib/msw/handlers/userHandlers.ts
  src/lib/msw/index.ts
  src/lib/msw/server.ts
Labels: ⚙️ chore

#27 [🔧 fix] axios 패키지 설치로 인한 의존성 업데이트
  pnpm-lock.yaml
Labels: 🔧 fix

#35 [🐞 hotfix] 로컬 빌드 시 발생하지 않는 오류가 vercel에서 발견되는 버그 발생 (#32)
  postcss.config.mjs
Labels: 🐞 hotfix

#31 [✨ feat] Axios instance 구현
  src/lib/axios/index.ts
Labels: ✨ feat

#38 [⚙️ chore] main 브랜치로 머지 시 액션 실행 테스트4 (#37)
  postcss.config.mjs
  src/lib/axios/index.ts
Labels: ⚙️ chore

#41 [🔧 fix] lefthook.yml의 prettier 명령어에 적용될 확장자 사이의 공백을 제거하고 모든 파일의 코드 포맷팅
  .storybook/preview.ts
  lefthook.yml
  public/mockServiceWorker.js
  src/constants/index.ts
  src/stories/Button.tsx
  src/stories/Header.tsx
Labels: 🔧 fix

#45 [✨ feat] HeaderIcon 컴포넌트 제작 (#43)
  src/assets/icons/CartIcon.tsx
  src/assets/icons/NationIcon.tsx
  src/assets/icons/UserIcon.tsx
  src/assets/icons/index.ts
  src/components/common/ClickText.tsx
  src/components/common/NavIcon.tsx
  src/components/layout/header/HeaderNavigation.tsx
  src/components/layout/header/TextHeader.tsx
  src/constants/paths.ts
  src/stories/NavIcon.stories.tsx
Labels: ✨ feat

#53 [✨ design] 중복 변수명을 사용하는 디자인 토큰 수정
  src/styles/token/colors/semantic.css
Labels: 💅 design

#55 [✨ feat] Footer 컴포넌트 구성 (#54)
  src/app/layout.tsx
  src/components/layout/footer/Footer.tsx
  src/components/layout/footer/FooterCompanyInfo.tsx
  src/components/layout/footer/FooterCustomerInfo.tsx
  src/components/layout/footer/FooterLogo.tsx
  src/components/layout/footer/FooterNav.tsx
  src/components/layout/footer/FooterPaymentInfo.tsx
  src/components/layout/footer/index.ts
  src/components/layout/header/Header.tsx
  src/components/layout/index.ts
  src/stories/ClickText.stories.ts
  src/stories/Footer.stories.ts
  src/stories/Header.stories.tsx
  src/stories/NavIcon.stories.tsx
  src/stories/SearchInput.stories.ts
  src/stories/TextHeader.stories.ts
Labels: ✨ feat

#56 [✨ feat] 인풋 컴포넌트 구현
  src/components/common/Input.tsx
  src/components/common/index.ts
  src/stories/Input.stories.ts
Labels: ✨ feat

#59 [✨ feat] TextHeader에 로그아웃 버튼 삽입 (#58)
  src/components/common/button/LogoutButton.tsx
  src/components/common/index.ts
  src/components/layout/header/TextHeader.tsx
Labels: ✨ feat

#63 [✨ design] spacing 디자인 토큰 40px 단위 추가
  src/components/layout/footer/Footer.tsx
  src/styles/token/spacing.css
Labels: 💅 design

#64 [✨ feat] 아이콘 매핑 컴포넌트 제작 (#61)
  src/assets/icons/index.ts
  src/assets/index.ts
  src/components/common/Icon.tsx
  src/components/common/button/Button.tsx
  src/components/common/header/SearchInput.tsx
  src/components/common/index.ts
  src/components/icons/BellIcon.tsx
  src/components/icons/CancelCircleIcon.tsx
  src/components/icons/CartIcon.tsx
  src/components/icons/CheckIcon.tsx
  src/components/icons/ChevronsDownIcon.tsx
  src/components/icons/ChevronsUpIcon.tsx
  src/components/icons/GoogleLogoIcon.tsx
  src/components/icons/HamburgerBarIcon.tsx
  src/components/icons/HeartFillIcon.tsx
  src/components/icons/HeartIcon.tsx
  src/components/icons/InfoIcon.tsx
  src/components/icons/JihyeIcon.tsx
  src/components/icons/LeftArrowIcon.tsx
  src/components/icons/LeftIcon.tsx
  src/components/icons/MinusIcon.tsx
  src/components/icons/NationIcon.tsx
  src/components/icons/NaverLogoIcon.tsx
  src/components/icons/PlusIcon.tsx
  src/components/icons/RightArrowIcon.tsx
  src/components/icons/RightIcon.tsx
  src/components/icons/SearchIcon.tsx
  src/components/icons/SmileIcon.tsx
  src/components/icons/StarFillIcon.tsx
  src/components/icons/StarGrayIcon.tsx
  src/components/icons/StarHalfIcon.tsx
  src/components/icons/UpArrowIcon.tsx
  src/components/icons/UserIcon.tsx
  src/components/icons/ViewCancelIcon.tsx
  src/components/icons/ViewIcon.tsx
  src/components/icons/XIcon.tsx
  src/components/icons/index.ts
  src/components/index.ts
  src/components/layout/footer/FooterLogo.tsx
  src/components/layout/header/Header.tsx
  src/components/layout/header/HeaderNavigation.tsx
  src/stories/Input.stories.ts
  src/stories/NavIcon.stories.tsx
  src/stories/button/Button.stories.ts
  src/stories/button/ClickTextButton.stories.ts
Labels: ✨ feat

#66 [✨ feat] 상품 더 보기 컴포넌트 제작 (#65)
  src/app/layout.tsx
  src/components/common/button/MoreViewButton.tsx
  src/components/common/index.ts
  src/components/layout/footer/Footer.tsx
  src/components/layout/header/Header.tsx
  src/stories/button/Button.stories.ts
Labels: ✨ feat

#68 [✨ feat] 위로 가기 버튼 추가 (#67)
  src/app/layout.tsx
  src/components/common/button/Button.tsx
  src/components/common/button/ScrollToTopButton.tsx
  src/components/common/index.ts
  src/stories/button/Button.stories.ts
  src/styles/globals.css
Labels: ✨ feat

#71 [🔧 fix] spacing 디자인 토큰 제거 및 padding, margin, gap 토큰 분리
  src/styles/token/spacing.css
Labels: 💅 design, 🔧 fix

#74 [🔧 fix] lefthook 검증에서 css 파일도 추가 (#73)
  lefthook.yml
Labels: 🔧 fix

#77 [🔧 fix] 오탈자로 인해 spacing 토큰의 css 속성값이 적용되지 않는 이슈 수정
  src/styles/token/spacing.css
Labels: 💅 design, 🔧 fix

#70 [✨ design] font 디자인 토큰 및 시맨틱 스타일 클래스 설정
  src/app/page.tsx
  src/styles/fonts.css
  src/styles/globals.css
Labels: 💅 design, ✨ feat

#80 [♻️ refactor] 사용되지 않는 디자인 토큰 값으로 인한 Footer 수정 (#79)
  src/components/layout/footer/Footer.tsx
  src/components/layout/footer/FooterCompanyInfo.tsx
  src/components/layout/footer/FooterCustomerInfo.tsx
  src/components/layout/footer/FooterNav.tsx
  src/components/layout/footer/FooterPaymentInfo.tsx
Labels: ♻️ refactor

#78 [✨ feat] 상품 썸네일 컴포넌트 제작 (#75)
  src/components/common/button/Button.tsx
  src/components/common/button/IconButton.tsx
  src/components/common/button/ScrollToTopButton.tsx
  src/components/icons/HeartIcon.tsx
  src/components/index.ts
  src/components/products/ProductThumbnail.tsx
  src/components/products/ProductThumbnailAction.tsx
  src/components/products/index.ts
  src/stories/product/ProductThumbnail.stories.tsx
Labels: ✨ feat

#86 [♻️ refactor] 폰트 디자인 토큰 정의 및 font 커스텀 클래스 리팩토링
  src/app/layout.tsx
  src/styles/fonts.css
  src/styles/token/font/primitive.css
Labels: ♻️ refactor

#85 [✨ feat] 상품 리스트와 아이템 제작 (#84)
  next.config.ts
  src/app/api/products/route.ts
  src/app/page.tsx
  src/components/layout/footer/index.ts
  src/components/products/ProductItem.tsx
  src/components/products/ProductItemSkeleton.tsx
  src/components/products/ProductList.tsx
  src/components/products/index.ts
  src/constants/endpoints.ts
  src/lib/msw/handlers/index.ts
  src/lib/msw/handlers/productsHandlers.ts
  src/mocks/.gitkeep
  src/mocks/index.ts
  src/mocks/products.ts
  src/services/.gitkeep
  src/services/fetchProducts.ts
  src/services/index.ts
  src/stories/product/ProductItem.stories.tsx
  src/stories/product/ProductList.stories.tsx
  src/types/index.ts
  src/types/productType.ts
  src/utils/calculateDiscountRate.ts
  src/utils/index.ts
Labels: ✨ feat

#83 [✨ design] 회원 인증 관련 페이지 UI 구현
  src/app/(auth)/layout.tsx
  src/app/(auth)/reset-password/page.tsx
  src/app/(auth)/signin/page.tsx
  src/app/(auth)/signup/page.tsx
  src/components/auth/SocialLoginButton.tsx
  src/components/common/Input.tsx
  src/components/common/button/ExtraButton.tsx
  src/components/common/index.ts
  src/constants/auth.ts
  src/constants/index.ts
  src/stories/Input.stories.ts
  src/stories/ResetPasswordPage.stories.ts
  src/stories/SigninPage.stories.ts
  src/stories/SignupPage.stories.ts
  src/styles/globals.css
Labels: ✨ feat

#89 [✨ feat] 추천 상품 아이템 제작 및 리스트 캐러셀화 (#88)
  package.json
  pnpm-lock.yaml
  src/app/page.tsx
  src/components/products/CarouselArrowButton.tsx
  src/components/products/ProductList.tsx
  src/components/products/RecommendCarousel.tsx
  src/components/products/RecommendProductItem.tsx
  src/components/products/RecommendProductList.tsx
  src/components/products/index.ts
  src/components/products/skeleton/ProductListSkeleton.tsx
  src/components/products/skeleton/RecommendProductSkeleton.tsx
  src/constants/endpoints.ts
  src/constants/index.ts
  src/constants/products.ts
  src/lib/msw/handlers/index.ts
  src/lib/msw/handlers/productsHandlers.ts
  src/mocks/products.ts
  src/services/fetchProducts.ts
  src/stories/product/RecommendProductItem.stories.tsx
  src/stories/product/RecommendProductList.stories.tsx
  src/styles/carousel.css
  src/styles/globals.css
Labels: ✨ feat

#92 [🔧 fix] app 디렉토리의 page.tsx 파일을 app/(root) 디렉토리 하위로 위치 이동
  src/app/(root)/page.tsx
Labels: 🐞 hotfix

#97 [✨ feat] 스위치 컴포넌트 제작 (#96)
  src/components/common/Switch.tsx
  src/components/common/index.ts
  src/stories/Switch.stories.tsx
Labels: ✨ feat

#95 [✨ feat] 드롭다운 컴포넌트 구현 (#94)
  src/components/common/Dropdown.tsx
  src/components/common/Icon.tsx
  src/components/common/RadioOption.tsx
  src/components/common/index.ts
  src/components/icons/RadioIcon.tsx
  src/components/icons/index.ts
  src/stories/Dropdown.stories.tsx
  src/stories/RadioOption.stories.tsx
  src/styles/globals.css
  src/types/iconType.ts
Labels: ✨ feat

#99 [🐞 hotfix] 디자인 토큰이 적용되지 않거나 오버라이팅 되는 이슈 수정
  src/styles/globals.css
  src/styles/token/border.css
Labels: 🔧 fix, 🐞 hotfix

#102 [🐞 hotfix] switch 컴포넌트의 'use client' 선언 누락으로 인한 이슈 해결
  src/components/common/Switch.tsx
Labels: 🔧 fix, 🐞 hotfix

#105 [✨ feat] 상품 상세 페이지 상단 주요 내용 담당 컴포넌트 제작 (#100)
  src/app/(root)/products/[productId]/page.tsx
  src/components/common/Dropdown.tsx
  src/components/common/button/ScrollToTopButton.tsx
  src/components/icons/RadioIcon.tsx
  src/components/products/RecommendCarousel.tsx
  src/components/products/RecommendProductList.tsx
  src/components/products/index.ts
  src/components/products/product-detail/ProductActions.tsx
  src/components/products/product-detail/ProductDetailItem.tsx
  src/components/products/product-detail/ProductHeader.tsx
  src/components/products/product-detail/ProductOptions.tsx
  src/components/products/product-detail/ProductPrice.tsx
  src/components/products/product-detail/ProductQuantity.tsx
  src/lib/msw/handlers/index.ts
  src/lib/msw/handlers/productsHandlers.ts
  src/mocks/products.ts
  src/services/fetchProducts.ts
  src/stories/product/ProductDetailItem.stories.tsx
  src/styles/carousel.css
  src/types/productType.ts
Labels: ✨ feat

#106 [✨ feat] MSW를 이용한 임시 api로 로그인/회원가입/비밀번호 재설정 기능 구현
  src/app/(auth)/reset-password/page.tsx
  src/app/(auth)/signin/page.tsx
  src/app/(auth)/signup/page.tsx
  src/components/auth/PoliciesInput.tsx
  src/components/auth/PwInput.tsx
  src/components/auth/ResetPwForm.tsx
  src/components/auth/SigninForm.tsx
  src/components/auth/SignupForm.tsx
  src/components/auth/VerifyCodeInput.tsx
  src/components/auth/VerifyEmailInput.tsx
  src/components/auth/index.ts
  src/components/index.ts
  src/constants/auth.ts
  src/constants/endpoints.ts
  src/lib/index.ts
  src/lib/msw/handlers/authHandlers.ts
  src/lib/msw/handlers/index.ts
  src/lib/msw/handlers/userHandlers.ts
  src/mocks/auth.ts
  src/mocks/index.ts
  src/schemas/.gitkeep
  src/schemas/auth/authSchema.ts
  src/schemas/auth/index.ts
  src/schemas/auth/resetPwSchema.ts
  src/schemas/auth/signinSchema.ts
  src/schemas/auth/signupSchema.ts
  src/schemas/auth/verifyEmailSchema.ts
  src/schemas/index.ts
  src/server-actions/auth/requestVerificationCodeAction.ts
  src/server-actions/auth/resetPwAction.ts
  src/server-actions/auth/signinAction.ts
  src/server-actions/auth/signupAction.ts
  src/server-actions/auth/verifyCodeAction.ts
  src/server-actions/index.ts
  src/services/authService.ts
  src/services/index.ts
  src/types/authType.ts
  src/types/index.ts
  src/utils/getMswEndpoint.ts
  src/utils/index.ts
Labels: ✨ feat

#109 [✨ feat] 프로그레스 바 컴포넌트 제작 (#108)
  src/components/common/Dropdown.tsx
  src/components/common/Icon.tsx
  src/components/common/StepProgressBar.tsx
  src/components/common/index.ts
  src/stories/StepProgressBar.stories.ts
Labels: ✨ feat

#113 [✨ feat] 체크박스 컴포넌트 제작 (#110)
  src/components/common/Checkbox.tsx
  src/components/common/index.ts
  src/stories/Checkbox.stories.ts
Labels: ✨ feat

#115 [✨ feat] JWT 관리 기능 구현
  package.json
  pnpm-lock.yaml
  src/lib/axios/index.ts
  src/mocks/auth.ts
  src/server-actions/auth/signinAction.ts
  src/services/index.ts
  src/services/tokenService.ts
Labels: ✨ feat

#120 [🐞 hotfix] 클라이언트 환경에서 실행되는 스토리북에 서버 로직이 포함되지 않도록 변경
  .storybook/main.ts
  package.json
  pnpm-lock.yaml
Labels: 🐞 hotfix

#121 [🐞 hotfix] 클라이언트 환경에서 실행되는 스토리북에 서버 로직이 포함되지 않도록 변경
  .storybook/main.ts
Labels: 🐞 hotfix

#123 [🐞 hotfix] 클라이언트 사이드에서 axiosInstance를 이용한 api 요청 경로 에러
  src/constants/endpoints.ts
  src/lib/axios/index.ts
Labels: 🐞 hotfix

#118 [✨ feat] 장바구니 페이지 제작 (#114)
  src/app/(root)/cart/page.tsx
  src/components/cart/CartHeader.tsx
  src/components/cart/CartInfo.tsx
  src/components/cart/CartItem.tsx
  src/components/cart/CartList.tsx
  src/components/cart/CartPaymentInfo.tsx
  src/components/cart/index.ts
  src/components/common/Checkbox.tsx
  src/components/common/StepProgressBar.tsx
  src/components/common/button/ExtraButton.tsx
  src/components/index.ts
  src/components/products/index.ts
  src/constants/endpoints.ts
  src/constants/paths.ts
  src/lib/msw/handlers/cartHandlers.ts
  src/lib/msw/handlers/index.ts
  src/lib/msw/handlers/productsHandlers.ts
  src/mocks/cart.ts
  src/mocks/index.ts
  src/services/cartService.ts
  src/services/index.ts
  src/services/productService.ts
  src/stores/.gitkeep
  src/stores/cartStore.ts
  src/stores/createCartMocks.ts
  src/stores/index.ts
  src/stories/NavIcon.stories.tsx
  src/stories/cart/CartInfo.stories.tsx
  src/stories/product/ProductItem.stories.tsx
  src/stories/product/ProductList.stories.tsx
  src/stories/product/RecommendProductItem.stories.tsx
  src/stories/product/RecommendProductList.stories.tsx
  src/types/cartType.ts
  src/types/index.ts
Labels: ✨ feat

#129 [✨ feat] 배포 환경에서도 msw가 동작하도록 변경 및 백엔드 서버 주소를 미리 적용
  src/app/layout.tsx
  src/constants/endpoints.ts
  src/lib/axios/index.ts
  src/utils/getMswEndpoint.ts
Labels: ✨ feat

#131 [⚙️ chore] 2차 마일스톤 | msw가 배포 환경에서도 동작하도록 변경 및 백엔드 baseURL 적용
  src/app/layout.tsx
  src/constants/endpoints.ts
  src/lib/axios/index.ts
  src/utils/getMswEndpoint.ts
Labels: ⚙️ chore

#124 [✨ feat] 서버와 클라이언트 컴포넌트 일관된 데이터 관리를 위한 tanstack query 정의
  package.json
  pnpm-lock.yaml
  src/app/(root)/layout.tsx
  src/app/(root)/page.tsx
  src/app/api/products/recommend/route.ts
  src/components/products/ProductListClientTemp.tsx
  src/components/products/ProductListWrapTemp.tsx
  src/components/products/RecommendCarousel.tsx
  src/components/products/RecommendProductItem.tsx
  src/components/products/RecommendProductList.tsx
  src/components/products/index.ts
  src/components/products/skeleton/RecommendProductSkeleton.tsx
  src/constants/endpoints.ts
  src/constants/index.ts
  src/constants/queries.ts
  src/lib/index.ts
  src/lib/tanstack.ts
  src/providers/.gitkeep
  src/providers/index.ts
  src/providers/reactQuery.tsx
  src/queries/authMutations.ts
  src/queries/index.ts
  src/queries/productsQueries.ts
  src/types/productType.ts
  src/utils/hydration.ts
  src/utils/index.ts
Labels: ✨ feat

#136 [🔧 fix] MSW 최초 렌더링 시 500 문제 해결
  src/app/layout.tsx
  src/instrumentation.ts
Labels: 🔧 fix

#138 [🔧 fix] 유틸 함수 getDehydratedState의 파리미터 queryOptions 타입이슈 해결과 유연성 확장
  src/app/(root)/page.tsx
  src/queries/productsQueries.ts
  src/utils/hydration.ts
Labels: 🔧 fix

#133 [♻️ refactor] 서버 응답값에 따른 데이터 구조 맞추기 (#132)
  src/app/(root)/cart/page.tsx
  src/app/(root)/page.tsx
  src/components/cart/CartItem.tsx
  src/components/cart/CartItemHeader.tsx
  src/components/cart/CartItemImage.tsx
  src/components/cart/CartItemOptions.tsx
  src/components/cart/CartItemPrice.tsx
  src/components/cart/CartItemQuantity.tsx
  src/components/products/ProductItem.tsx
  src/components/products/ProductList.tsx
  src/components/products/ProductListClientTemp.tsx
  src/components/products/RecommendCarousel.tsx
  src/components/products/RecommendProductItem.tsx
  src/lib/msw/handlers/productsHandlers.ts
  src/mocks/cart.ts
  src/mocks/products.ts
  src/queries/index.ts
  src/stores/createCartMocks.ts
  src/types/cartType.ts
Labels: ♻️ refactor

#140 [🐞 hotfix] 클라이언트 컴포넌트 refetch data 렌더링 에러
  src/app/(root)/page.tsx
  src/components/products/skeleton/RecommendProductSkeleton.tsx
  src/constants/endpoints.ts
  src/lib/axios.ts
Labels: 🔧 fix, 🐞 hotfix

#142 [✨ feat] 비회원/회원에 따라 장바구니 추가, 조회 적용 (#141)
  src/app/(root)/cart/page.tsx
  src/app/api/cart/route.ts
  src/app/api/products/[productId]/route.ts
  src/components/cart/CartInfo.tsx
  src/components/cart/CartItem.tsx
  src/components/cart/CartItemQuantity.tsx
  src/components/cart/CartList.tsx
  src/components/products/ProductThumbnailAction.tsx
  src/components/products/product-detail/ProductActions.tsx
  src/components/products/product-detail/ProductDetailItem.tsx
  src/components/products/product-detail/ProductOptions.tsx
  src/components/products/product-detail/ProductQuantity.tsx
  src/constants/queries.ts
  src/hooks/common/index.ts
  src/hooks/common/useCart.ts
  src/mocks/cart.ts
  src/mocks/products.ts
  src/queries/cartQueries.ts
  src/queries/index.ts
  src/services/cartService.ts
  src/stores/cartStore.ts
  src/stores/createCartMocks.ts
  src/stories/product/ProductDetailItem.stories.tsx
  src/stories/product/ProductItem.stories.tsx
  src/stories/product/ProductList.stories.tsx
  src/stories/product/RecommendProductItem.stories.tsx
  src/stories/product/RecommendProductList.stories.tsx
  src/types/cartType.ts
  src/types/productType.ts
Labels: ✨ feat

#146 [✨ feat] orders와 payments의 API Schema, 타입 정의
  src/types/index.ts
  src/types/ordersType.ts
  src/types/paymentsType.ts
Labels: ✨ feat

#148 [✨ feat] 비회원/회원에 따른 장바구니 삭제 로직 추가 (#147)
  src/components/cart/CartItem.tsx
  src/components/products/product-detail/ProductPrice.tsx
  src/hooks/common/useCart.ts
  src/services/cartService.ts
Labels: ✨ feat

#152 [✨ feat] api request body의 json 키를 camelCase로 수정
  src/lib/msw/handlers/authHandlers.ts
  src/services/authService.ts
Labels: ✨ feat

#154 [⚙️ chore] 이미지 외부 도메인 허용 설정 추가
  next.config.ts
Labels: ⚙️ chore

#156 [✨ feat] 장바구니, 상품 상세 페이지의 주문하기 CTA flow 추가
  src/components/cart/CartInfo.tsx
  src/components/common/Toast.tsx
  src/components/products/product-detail/ProductActions.tsx
  src/constants/paths.ts
  src/hooks/common/useCart.ts
  src/stores/cartStore.ts
  src/types/cartType.ts
  src/utils/calculate.ts
  src/utils/format.ts
  src/utils/index.ts
  src/utils/toast.tsx
Labels: ✨ feat

#158 [✨ feat] 장바구니 조회/삭제/추가 로직에 쿼리 적용 (#157)
  src/app/(root)/cart/page.tsx
  src/app/api/cart/route.ts
  src/components/cart/CartInfo.tsx
  src/components/cart/CartList.tsx
  src/components/products/product-detail/ProductActions.tsx
  src/hooks/common/useCart.ts
  src/lib/msw/handlers/cartHandlers.ts
  src/queries/cartQueries.ts
  src/stores/cartStore.ts
Labels: ✨ feat

#143 [✨ feat] 쇼핑몰 FAQ 조회 페이지 구현
  src/app/(root)/faqs/error.tsx
  src/app/(root)/faqs/page.tsx
  src/components/faqs/CategoryFilter.tsx
  src/components/faqs/CategoryFilterItem.tsx
  src/components/faqs/FaqAccordion.tsx
  src/components/faqs/FaqAccordionAnswer.tsx
  src/components/faqs/FaqAccordionItemQuestion.tsx
  src/components/faqs/SearchedFaq.tsx
  src/components/faqs/SubCategoryFilter.tsx
  src/components/faqs/SubCategoryFilterItem.tsx
  src/components/faqs/index.ts
  src/components/index.ts
  src/constants/endpoints.ts
  src/server-actions/faq/faqSearchAction.ts
  src/server-actions/index.ts
  src/services/faqService.ts
  src/services/index.ts
  src/styles/globals.css
  src/types/faqType.ts
  src/types/index.ts
Labels: ✨ feat

#161 [✨ feat] 상품 도메인에 쿼리 적용 (#160)
  src/app/(root)/page.tsx
  src/app/(root)/products/[productId]/page.tsx
  src/components/common/button/MoreViewButton.tsx
  src/components/products/ClientProductList.tsx
  src/components/products/ProductList.tsx
  src/components/products/index.ts
  src/components/products/product-detail/ClientProductDetail.tsx
  src/components/products/product-detail/ProductActions.tsx
  src/components/products/skeleton/ProductListSkeleton.tsx
  src/constants/endpoints.ts
  src/lib/msw/handlers/productsHandlers.ts
  src/queries/productsQueries.ts
  src/services/cartService.ts
  src/services/productService.ts
  src/stores/cartStore.ts
  src/stores/createCartMocks.ts
Labels: ✨ feat

#167 [🐞 hotfix] 회원일 경우에서 장바구니에서 발생하는 오류 수정 (#166)
  src/app/api/cart/[cartItemId]/route.ts
  src/app/api/cart/route.ts
Labels: 🐞 hotfix

#177 [♻️ refactor] 상품 데이터 구조에 맞춰 가격 정보 수정 (#176)
  .storybook/preview.tsx
  src/components/cart/CartInfo.tsx
  src/components/cart/CartItemPrice.tsx
  src/components/cart/CartPaymentInfo.tsx
  src/components/products/ProductItem.tsx
  src/components/products/RecommendProductItem.tsx
  src/components/products/product-detail/ProductDetailItem.tsx
  src/components/products/product-detail/ProductPrice.tsx
  src/services/cartService.ts
  src/stores/cartStore.ts
  src/stories/product/ProductDetailItem.stories.tsx
  src/stories/product/ProductItem.stories.tsx
  src/stories/product/ProductList.stories.tsx
  src/stories/product/RecommendProductItem.stories.tsx
  src/stories/product/RecommendProductList.stories.tsx
  src/types/productType.ts
  src/utils/calculate.ts
Labels: ♻️ refactor

#174 [✨ feat] 상품 카테고리에 대한 카테고리 생성 및 연동 (#169)
  src/app/(root)/page.tsx
  src/app/(root)/products/page.tsx
  src/app/api/categories/[categoryId]/products/route.ts
  src/app/api/categories/route.ts
  src/components/category/CategoryProductList.tsx
  src/components/category/CategorySkeleton.tsx
  src/components/category/ClientCategoryProductList.tsx
  src/components/category/ProductCategory.tsx
  src/components/common/Icon.tsx
  src/components/icons/ClothesIcon.tsx
  src/components/icons/CosmeticIcon.tsx
  src/components/icons/DigitalIcon.tsx
  src/components/icons/GroceryIcon.tsx
  src/components/icons/NecessityIcon.tsx
  src/components/icons/index.ts
  src/components/products/index.ts
  src/constants/endpoints.ts
  src/constants/paths.ts
  src/constants/queries.ts
  src/queries/categoryQueries.ts
  src/queries/index.ts
  src/services/categoryService.ts
  src/services/index.ts
  src/types/categoryType.ts
  src/types/iconType.ts
  src/types/index.ts
Labels: ✨ feat

#178 [✨ feat] 상품별 리뷰 조회 구현
  src/app/(auth)/layout.tsx
  src/app/(root)/products/[productId]/page.tsx
  src/components/common/Icon.tsx
  src/components/icons/NegativeIcon.tsx
  src/components/icons/PositiveIcon.tsx
  src/components/icons/index.ts
  src/components/reviews/index.ts
  src/components/reviews/product-review/AverageReview.tsx
  src/components/reviews/product-review/ProductReview.tsx
  src/components/reviews/product-review/ReviewBadge.tsx
  src/components/reviews/product-review/ReviewFilter.tsx
  src/components/reviews/product-review/ReviewItem.tsx
  src/components/reviews/product-review/ReviewLikeButton.tsx
  src/components/reviews/product-review/ReviewList.tsx
  src/components/reviews/product-review/ReviewRatingBar.tsx
  src/components/reviews/product-review/StarRating.tsx
  src/constants/endpoints.ts
  src/server-actions/index.ts
  src/server-actions/review/reviewLikeAction.ts
  src/services/reviewService.ts
  src/styles/token/colors/semantic.css
  src/types/iconType.ts
  src/utils/calculateRelativeTime.ts
  src/utils/index.ts
  src/utils/reviewCache.ts
Labels: ✨ feat

#182 [♻️ refactor] 상품 카테고리 svg 수정 및 스타일 수정 (#181)
  next.config.ts
  src/app/(root)/page.tsx
  src/components/category/CategorySkeleton.tsx
  src/components/category/ProductCategory.tsx
  src/components/icons/ClothesIcon.tsx
  src/components/icons/CosmeticIcon.tsx
  src/components/icons/DigitalIcon.tsx
  src/components/icons/GroceryIcon.tsx
  src/components/icons/NecessityIcon.tsx
  src/components/products/ProductList.tsx
Labels: ♻️ refactor

#185 [✨ feat] not-found 페이지 제작 (#183)
  src/app/not-found.tsx
  src/components/common/Icon.tsx
  src/components/icons/NotFoundIcon.tsx
  src/components/icons/index.ts
  src/stories/NotFoundPage.stories.tsx
  src/types/iconType.ts
Labels: ✨ feat

#187 [✨ feat] 결제할 상품 리스트 도착예상일 별 그룹화 리스팅과 order 관련 스토리북 컴포넌트 추가
  src/app/(root)/checkout/page.tsx
  src/components/orders-payments/OrderProductList/OrderProductList.tsx
  src/components/orders-payments/OrderProductList/OrderProductListGroup.tsx
  src/components/orders-payments/OrderProductList/ProductAmoutInfo.tsx
  src/components/orders-payments/OrderProductList/ProductOptionInfo.tsx
  src/components/orders-payments/OrderProductList/index.ts
  src/components/orders-payments/index.ts
  src/stories/orders/OrderProductListGroup.stories.tsx
  src/types/ordersType.ts
  src/utils/dataTransformUtils.ts
  src/utils/index.ts
Labels: 💅 design, ✨ feat

#189 [♻️ refactor] 상품 일부 컴포넌트 반응형 적용 및 쿼리 구조 변경 (#186)
  public/.gitkeep
  src/app/(root)/cart/page.tsx
  src/app/(root)/page.tsx
  src/app/(root)/products/page.tsx
  src/components/category/CategoryProductList.tsx
  src/components/category/ClientCategoryProductList.tsx
  src/components/category/ProductCategory.tsx
  src/components/common/Icon.tsx
  src/components/icons/TinyLogoIcon.tsx
  src/components/icons/index.ts
  src/components/products/ClientProductList.tsx
  src/components/products/ProductListClientTemp.tsx
  src/components/products/ProductListWrapTemp.tsx
  src/components/products/RecommendCarousel.tsx
  src/components/products/RecommendProductList.tsx
  src/components/products/index.ts
  src/components/products/skeleton/RecommendProductSkeleton.tsx
  src/constants/products.ts
  src/styles/carousel.css
  src/types/iconType.ts
Labels: ♻️ refactor

#191 [✨ feat] 인증 API 수정사항을 반영 및 UI 개선
  src/app/(auth)/layout.tsx
  src/app/(auth)/signup/page.tsx
  src/components/auth/PoliciesInput.tsx
  src/components/auth/PwInput.tsx
  src/components/auth/ResetPwForm.tsx
  src/components/auth/SigninForm.tsx
  src/components/auth/SignupForm.tsx
  src/components/auth/SocialLoginButton.tsx
  src/components/auth/TermItem.tsx
  src/components/auth/TermsInput.tsx
  src/components/auth/VerifyCodeInput.tsx
  src/components/auth/VerifyEmailInput.tsx
  src/components/common/Input.tsx
  src/constants/auth.ts
  src/constants/endpoints.ts
  src/schemas/auth/authSchema.ts
  src/schemas/auth/requestVerifySchema.ts
  src/server-actions/auth/requestVerificationCodeAction.ts
  src/server-actions/auth/signinAction.ts
  src/server-actions/auth/signupAction.ts
  src/services/authService.ts
  src/types/authType.ts
Labels: ✨ feat

#192 [✨ feat] 리뷰 감성분석 기능 추가
  src/components/common/button/Button.tsx
  src/components/reviews/create-review/CreateReviewButtonBox.tsx
  src/components/reviews/create-review/ReviewContent.tsx
  src/components/reviews/product-review/ReviewBadge.tsx
  src/components/reviews/product-review/ReviewItem.tsx
  src/components/reviews/product-review/ReviewLikeButton.tsx
  src/constants/endpoints.ts
  src/server-actions/index.ts
  src/server-actions/review/reviewLikeAction.ts
  src/server-actions/review/sentimentFeedbackAction.ts
  src/services/reviewService.ts
Labels: ✨ feat

#198 [✨ feat] 상품 상세 페이지에 상품 정보 테이블 및 이미지 추가 (#197)
  src/app/(root)/products/[productId]/page.tsx
  src/components/products/index.ts
  src/components/products/product-detail/ProductDetailInfo.tsx
  src/utils/format.ts
Labels: ✨ feat

#195 [✨ feat] 상품 리스트에 목록 가상화 적용 (#194)
  package.json
  pnpm-lock.yaml
  src/components/category/ClientCategoryProductList.tsx
  src/components/products/ClientProductList.tsx
  src/constants/products.ts
  src/hooks/common/index.ts
  src/hooks/common/useProductListVirtualizer.ts
Labels: ✨ feat

#196 [✨ feat] 마이페이지 의 첫페이지인 주문내역 조회 페이지의 기능과 반응형 UI 구현
  src/app/(root)/checkout/page.tsx
  src/app/(root)/layout.tsx
  src/app/(root)/my/orders/page.tsx
  src/components/cart/CartHeader.tsx
  src/components/common/Badge.tsx
  src/components/common/Breadcrumb.tsx
  src/components/common/PageTitle.tsx
  src/components/common/SectionTitle.tsx
  src/components/common/button/ExtraButton.tsx
  src/components/common/index.ts
  src/components/index.ts
  src/components/layout/footer/Footer.tsx
  src/components/layout/header/Header.tsx
  src/components/mypage/MypageHeader.tsx
  src/components/mypage/index.ts
  src/components/orders-payments/CheckoutHeader.tsx
  src/components/orders-payments/OrderHistoryList/OrderHistoryList.tsx
  src/components/orders-payments/OrderHistoryList/OrderHistoryListGroup.tsx
  src/components/orders-payments/OrderHistoryList/OrdersActions.tsx
  src/components/orders-payments/OrderHistoryList/OrdersExtraActions.tsx
  src/components/orders-payments/OrderHistoryList/index.ts
  src/components/orders-payments/OrderProductList/OrderProductList.tsx
  src/components/orders-payments/OrderProductList/OrderProductListGroup.tsx
  src/components/orders-payments/ProductAmoutInfo.tsx
  src/components/orders-payments/ProductName.tsx
  src/components/orders-payments/ProductOptionInfo.tsx
  src/components/orders-payments/SectionHeadingTitle.tsx
  src/components/orders-payments/index.ts
  src/lib/msw/handlers/index.ts
  src/lib/msw/handlers/ordersHandlers.ts
  src/mocks/index.ts
  src/mocks/orders.ts
  src/styles/globals.css
  src/styles/layout.css
  src/types/ordersType.ts
  src/utils/dataTransformUtils.ts
  src/utils/genertate.ts
  src/utils/index.ts
Labels: ✨ feat

#200 [✨ feat] 메인페이지에 챗봇 아이콘 삽입 (#199)
  src/app/(root)/page.tsx
  src/components/common/Icon.tsx
  src/components/icons/MainPageChatbotDesktopIcon.tsx
  src/components/icons/MainPageChatbotMobileIcon.tsx
  src/components/icons/index.ts
  src/components/index.ts
  src/components/main/MainIntroduction.tsx
  src/components/main/index.ts
  src/queries/authMutations.ts
  src/stories/SignupPage.stories.ts
  src/stories/orders/OrderProductListGroup.stories.tsx
  src/types/iconType.ts
Labels: ✨ feat

#202 [♻️ refactor] 비회원일 경우 장바구니에 담기는 상품 개수 제한 (#201)
  src/services/cartService.ts
Labels: ♻️ refactor

#205 [♻️ refactor] 비회원일 경우 결제 페이지로 이동하지 못하게 막기 (#204)
  src/components/cart/CartInfo.tsx
  src/stories/cart/CartInfo.stories.tsx
Labels: ♻️ refactor

#207 [♻️ refactor] 이름 바뀐 아이콘으로 변경 (#206)
  src/app/(root)/cart/page.tsx
  src/app/(root)/products/[productId]/page.tsx
  src/app/layout.tsx
  src/components/common/Icon.tsx
  src/components/common/Logo.tsx
  src/components/icons/JihyeIcon.tsx
  src/components/icons/TuttiIcon.tsx
  src/components/icons/index.ts
  src/components/layout/footer/FooterLogo.tsx
  src/components/products/ProductItem.tsx
  src/components/products/RecommendProductItem.tsx
  src/components/products/product-detail/ProductDetailItem.tsx
  src/constants/products.ts
  src/hooks/common/useProductListVirtualizer.ts
  src/styles/token/spacing.css
Labels: ♻️ refactor
